### PR TITLE
Update dependencies babel 7

### PR DESCRIPTION
**Pull request by EECOLOR**
Also updated some other dependencies.

### CODE REVIEW

**Comment by klaasman** [comment]
as discussed: let's test these changes (both development as deployment) with some real world codebases before merging

**Comment by klaasman** [comment]
Not sure if it should be part of this PR, but eslint needs some attention:

image

**Comment by klaasman** [comment]
Take a look at: https://babeljs.io/docs/en/babel-plugin-proposal-decorators#decoratorsbeforeexport

previously we had decorators before exports, but now it defaults to exports before decorators. Here's a discussion about this: https://github.com/tc39/proposal-decorators/issues/69.

I don't have a strong opinion about the issue, but it would be an easier transition if we stick to the old way.

**Comment by EECOLOR** [comment]
The setting is set to classic right? As far as I can tell classic is 'before export' anyway.

**Comment by EECOLOR** [comment]
The setting is set to classic right? As far as I can tell classic is 'before export' anyway.

**Comment by EECOLOR** [comment]
> There appear to be some changes regarding to css-modules values variables. Previously the @value syntax worked out of the box, but now it seems to be missing.

It should still work when I look at the source code: https://github.com/css-modules/css-modules-loader-core/blob/master/src/index.js

**Comment by EECOLOR** [comment]
I think the problem is caused by having both postcss 6 and 7...

Does the postcss nightmare ever stop?

**Comment by EECOLOR** [comment]
Ok, so the problem is nasty.

We waited quite some time for cssnano to move to postcss 6. When it did (as version 4 was released) they quite quickly moved to postcss 7. A lot of the 4.0 issues have been fixed later (4.1.x), part of the release that contained these fixes was the move to postcss 7.

Now [postcss-modules](https://github.com/css-modules/postcss-modules/blob/master/package.json) or actually [css-modules-loader-core](https://github.com/css-modules/css-modules-loader-core/blob/master/package.json) (and it's dependencies) are still stuck on postcss 6. It seems however that this project is problematic: https://github.com/css-modules/css-modules-loader-core/issues/174

Another one keeping postcss 6 is [cssnext](https://github.com/MoOx/postcss-cssnext/blob/master/package.json): [Deprecating cssnext](https://moox.io/blog/deprecating-cssnext/).

I am not seeing a clear way out. When I push away the depression that creeps up and look at the related community from a non-judging / observational standpoint it seems this is not the right technology to be using. I'm sure we are not alone in this struggle, but we should be looking for one of the following:
- An alternative
- Copy all related code we need into a repository and clean it up

**Comment by EECOLOR** [comment]
https://github.com/css-modules/css-modules/issues/306

**Comment by EECOLOR** [comment]
There is some movement on the css module issues

**Comment by EECOLOR** [comment]
It seems there is a solution available for css modules. The webpack css loader plugin solves it by working around the `postcss-modules` plugin: https://github.com/webpack-contrib/css-loader/blob/master/src/index.js#L77

This should also simplify our css loader plugin.

**Comment by EECOLOR** [comment]
Support https://github.com/css-modules/postcss-modules-extract-imports is tricky, so we won't add it

**Comment by EECOLOR** [comment]
The problem of this branch is that it introduces 2 versions of the postcss library. I started working on a solution (going without the unsupported css modules plugin) in the `eecolor-css-troubles` branch. That work needs to be complete before we can merge it.

A shortterm alternative would be to update non-css related dependencies.

**Comment by EECOLOR** [comment]
Closed in favor of #159

**Pull request closed without merging**
