### PR TITLE
allow custom properties in child selectors

### PR DESCRIPTION
**Pull request by EECOLOR**
While we should not use custom properties in regular projects yet because of browser support it should be possible to define them without the linter giving a warning.

Before this change the error was that only layout related properties are allowed. That error does not seem fitting to a custom property.

Ohw and for internal applications we can use them.

If you are interested, this is the use case I encountered it:

```css
.component {
  & > .taskBody:not(:last-child) {
    --margin-bottom: 20px;
  }
}

.componentTaskBody {
  &::after { /* work-around for non functioning margin-bottom on tbody */
    content: '';
    display: block;
    margin-bottom: var(--margin-bottom);
  }
}
```

### CODE REVIEW

**Comment by JoostKiens** [comment]
The code look fine to me (as far as I can follow), but I'm not sure I agree with the use case.

If the element is a `tbody`, use a padding. There's no such thing as a margin between table elements (`border-spacing` comes close). Seems your solution is using a margin as a padding anyway, it's in the `border-box` of the element.

```css
.componentTaskBody { padding-bottom: 20px; }
```

**Comment by EECOLOR** [comment]
> Seems your solution is using a margin as a padding anyway, it's in the border-box of the element.

Not according to our rules. I have multiple `thead` and `tbody` elements in a single table. I want spacing after all (but the last) `tbody`. That space should not be part of the `tbody`.

> If the element is a tbody, use a padding.

I might be able to get away with that in my specific use case

> There's no such thing as a margin between table elements (border-spacing comes close).

Haha, yeah, I noticed. There should be though. The specs allow for multiple `thead` and `tbody` elements. And `margin-bottom` does work on `tr`.

**Comment by peeke** [comment]
@EECOLOR Is this still relevant? Came across this when reviewing PRs. On a side note, we can probably start allowing custom properties in our projects. Only Opera Mini and IE11 lack support. @martijndevalk from time to time has some pretty cool use cases, which can be used while still keeping content accessible for these browsers.

**Comment by EECOLOR** [comment]
@peeke Yes, it is still relevant. I simply didn't have the time to integrate it yet.

**Pull request merged**
